# Generated by Django 4.2 on 2026-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress'), ('wellbeing', 'Well-being')], max_length=50)),
                ('summary', models.TextField(help_text='Short intro shown on landing pages')),
                ('content', models.TextField(help_text='Full article content')),
                ('assessment_type', models.CharField(blank=True, choices=[('PHQ-9', 'PHQ-9'), ('GAD-7', 'GAD-7')], help_text='Optional self-assessment link', max_length=20, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disorders', models.ManyToManyField(blank=True, related_name='articles', to='disorders.disorder')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
