# Generated by Django 4.2 on 2026-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disorders', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disorders',
            field=models.ManyToManyField(blank=True, related_name='articles', to='disorders.disorder'),
        ),
    ]
