# Generated by Django 4.2 on 2026-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='description',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='name',
            field=models.CharField(choices=[('PHQ9', 'Patient Health Questionnaire-9'), ('GAD7', 'Generalized Anxiety Disorder-7'), ('AUDIT', 'Alcohol Use Disorders Identification Test'), ('BURNOUT', 'Burnout Assessment')], max_length=20, unique=True),
        ),
    ]
