# Generated by Django 4.2 on 2026-02-11 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={},
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='severity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
