# Generated by Django 4.2 on 2026-02-13 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0003_alter_assessmentresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='recommended_articles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='recommended_treatments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='risk_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='severity',
            field=models.CharField(max_length=255),
        ),
    ]
