# Generated by Django 4.2 on 2026-02-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0004_assessmentresult_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='severity',
            field=models.CharField(max_length=100),
        ),
    ]
