# Generated by Django 4.2 on 2026-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_riskalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationRiskStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
