# Generated by Django 4.2 on 2026-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('treatment_type', models.CharField(choices=[('curative', 'Curative'), ('preventive', 'Preventive'), ('promotive', 'Promotive')], max_length=20)),
                ('description', models.TextField(help_text='High-level explanation of the treatment approach')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disorders', models.ManyToManyField(blank=True, related_name='treatments', to='disorders.disorder')),
            ],
            options={
                'ordering': ('treatment_type', 'name'),
            },
        ),
    ]
